### ISSUE TITLE
V4 Api does not return schedules after special schedule ends if special schedule is not week and returns special schedule as wrong date

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirkanta-api#4] opened 2019-02-13 14:03 UTC
If special schedule is for eq. one day instead of a week, the API does not return the normal schedules that occur after the special schedule.

https://api.kirjastot.fi/v4/schedules?library=85306&lang=fi&period.start=2w&period.end=2w&refs=period&limit=500&pretty

https://gist.github.com/olli-suutari-jkl/a844cb002b197f6fb3b0cdc3821df324

![image](https://user-images.githubusercontent.com/42733913/52715492-3eba0b00-2fa5-11e9-97bd-856580a84f03.png)

![image](https://user-images.githubusercontent.com/42733913/52715371-fc90c980-2fa4-11e9-8b8d-19cb7e114b96.png)

![image](https://user-images.githubusercontent.com/42733913/52715392-087c8b80-2fa5-11e9-94a9-fb9ec573c641.png)

V3 appears to be working...
![image](https://user-images.githubusercontent.com/42733913/52715620-8c367800-2fa5-11e9-8f81-7fab91b152ad.png)

**Comment by sjuvonen** [comment] 2019-02-25 08:31
Sorry, I did not receive any email notifications. We have had issues with schedules but I presume most of them are fixed by now. I'll check later today if these problems are still present or not.

**Comment by olli-suutari-jkl** [comment] 2019-04-03 12:27
@sjuvonen  This is still an issue.

https://api.kirjastot.fi/v4/schedules?library=85346&lang=en&period.start=4w&period.end=4w&refs=period&limit=5000&pretty
https://gist.github.com/olli-suutari-jkl/a2244299990cbabae13093d9baa2224a

Only returns days from Monday to Wednesday.

Fetching schedules after the special schedules does not return any items:

https://api.kirjastot.fi/v4/schedules?library=85346&lang=en&period.start=5w&period.end=5w&refs=period&limit=5000&pretty

returns:
{
    "type": "schedules",
    "total": null,
    "items": [],
    "refs": {
        "period": {}
    }
}

https://kirkanta.kirjastot.fi/library/85346/periods

![image](https://user-images.githubusercontent.com/42733913/55477708-7139c900-5622-11e9-843d-fd64dae042fe.png)


![image](https://user-images.githubusercontent.com/42733913/55478302-0a1d1400-5624-11e9-8581-fc9d1e1e9698.png)


In https://hakemisto.kirjastot.fi/viitasaari/viitasaari it is not possible to fetch schedules after week 19.

I have ~~(in a moment)~~ temporary restricted the fetching of the schedules up to 3 weeks in our own version:
https://www.keskikirjastot.fi/web/arena/kirjastot?viitasaaren-kirjasto

Futhermore, if this is not fixed within a week, I will need to instruct the Keski-libraries against using periods shorter than one week, until this is fixed.

Naturally, the Finna-view is broken too:
https://www.finna.fi/OrganisationInfo/Home?id=Keski#85346

**Comment by sjuvonen** [comment] 2019-04-08 02:46
Hi. I will check later today if the bug is still present. I made another fix last night related to issues with exceptional schedules, so this might be solved too, but I have to verify it.

**Comment by sjuvonen** [comment] 2019-04-08 13:52
There was another regression that was fixed a few moments ago..........................

**Comment by olli-suutari-jkl** [comment] 2019-05-02 11:13
@sjuvonen Apparently there are still some "bugs".

After re-creating the schedules for Kuhmoinen (https://github.com/libraries-fi/kirkanta/issues/9), only 4 days are fetched instead of the whole week, and the schedules after this week just return null. 

https://www.keskikirjastot.fi/web/arena/kirjastot?kuhmoisten-paakirjasto
![image](https://user-images.githubusercontent.com/42733913/57071847-5e2f1d00-6ce4-11e9-9648-b97080ce1179.png)


https://api.kirjastot.fi/v4/schedules?library=85020&lang=en&period.start=0w&period.end=0w&refs=period&limit=5000&pretty

https://gist.github.com/olli-suutari-jkl/406b18ca79e9592b5e1679c4069cb75b
Note: Thursday is Closed ("Sunday");


https://api.kirjastot.fi/v4/schedules?library=85020&lang=en&period.start=1w&period.end=1w&refs=period&limit=5000&pretty
{
    "type": "schedules",
    "total": null,
    "items": [],
    "refs": {
        "period": {}
    }
}


https://kirkanta.kirjastot.fi/library/85020/periods/333805/edit

![image](https://user-images.githubusercontent.com/42733913/57071822-4b1c4d00-6ce4-11e9-9702-f015f3f45c16.png)

**Comment by olli-suutari-jkl** [comment] 2019-05-02 11:34
Interestingly modifying the day schedules or descriptions does not have any result in the results what so ever. However, the schedule "description" updates normally. 

![image](https://user-images.githubusercontent.com/42733913/57072741-62a90500-6ce7-11e9-8563-fac43acebcab.png)

**Comment by olli-suutari-jkl** [comment] 2019-05-02 11:44
I deleted the schedule (a few minutes ago) and re-created it, but now the api does not return anything. 
Perhaps there is some sort of a delay?  😕 

https://kirkanta.kirjastot.fi/library/85020/periods
https://kirkanta.kirjastot.fi/library/85020/periods/333813/edit

https://api.kirjastot.fi/v4/schedules?library=85020&lang=en&period.start=0w&period.end=0w&refs=period&limit=5000

schedule.js:185 {type: "schedules", total: null, items: Array(0), refs: {…}}items: []refs: {period: {…}}total: nulltype: "schedules"__proto__: Object

**Comment by sjuvonen** [comment] 2019-05-02 12:14
There  is no guarantee nor promise of realtime updates. Technically, in this case, it is a bug if the schedules indeed are not updated after saving the period, but small delays are basically allowed if we were to employ internal caching**(*)** or whatever. Right now there is a fallback mechanism that triggers schedule updates every fifteen minutes, so any changes should be applied by that time.

It is still not reliable to expect that users can verify their input by looking at output at another "client application" that reads its data via the API. This is also why circumventing caching headers just to please insecure users at the expense of all others is not a viable solution. 

There was a plan to implement a calendar view for schedules directly into Kirkanta but it has been postponed.

**(*)** Technically everything IS cached already, but for the most part this cache is updated every time a user saves changes in the UI.

**Comment by olli-suutari-jkl** [comment] 2019-05-02 13:35
The v4 api is still returning null, v3 api howevers appears to be working:
https://www.finna.fi/OrganisationInfo/Home?id=Keski#85020

--------------------------------------------------------------------------------

Off topic: Regarding the recent caching changes in https://github.com/olli-suutari-jkl/jyvaskyla.fi.kirjasto  and earlier discussion here: https://github.com/libraries-fi/kirkanta-api/issues/3

The loading time for the widgets consists mostly of libraries (jQuery, Bootstrap, .less etc…)  and images. (See: https://imgur.com/a/1pNgIio ). The “load time” for 1 mb/s connection is about a few seconds, and I consider that to be reasonable. 

Even if caching of the api requests would speed up them by 30%, it wouldn’t have a very large difference on the overall loading time. Improving the widget performance is on my To Do List, and I will be investigating the impact of the api requests and caching too. It is also possible that I'm underestimating the affect of caching.

I suppose the priorities could look a bit like this:
1. Update the city/lib list fetching to use v4 api (text compression, I tried this at some point but there were issues.)
2. Re-do the image slider with lazy loading and smaller images (thumbnails) for small slider.
3. Generate “bundles” for all .js and .css code.
4. Improve the caching.

However, before the performance improvements I should be making sure that the widgets are compatible with WCAG 2.0 standards. I’m also planning on re-writing the whole solution, so it no longer uses iframes. (iframes were originally used because no scripting was allowed on Jyvaskyla.fi).

I'm currently working mostly on an another work project, but I'm looking forwards to spending more time with the widgets during the summer.

**Comment by sjuvonen** [comment] 2019-05-02 14:25
Yeah, sorry, I misrecalled the configuration. There seems to be a fallback option for v4 that only runs once per day at 10 am. For an older API there is a quarter-hourly fallback due to different requirements. (Right now the schedules are back up because I ran the script manually to check for problems.)

I'll try to figure out the reason behind problematic schedule updates, but I think I've tried to do that before too. On my development machine there are no problems but for some reason the updates fail in production.

**Comment by sjuvonen** [comment] 2019-05-02 14:28
Well it's a third world problem mostly, but when you have ping of a few seconds and packet loss close to 95 %, everything crawls to a halt. Then caching is the what makes or breaks the user experience.

**Comment by olli-suutari-jkl** [comment] 2019-05-02 14:54
Good luck on tracking down the issue, bugs can be nasty. 🍀 

I can confirm that:
https://api.kirjastot.fi/v4/schedules?library=85020&lang=en&period.start=0w&period.end=0w&refs=period&limit=5000&pretty
started returning the schedules around 17.23. 

I removed the day infos (17.24) from wed, thu and sat, but they are not yet removed from the results.  (Presumably fallback is still set to 10 am and the main mechanism has issues for whatever reason). 

Updating the schedule description however updates "Instantly".

Regarding the optimizations, my mindset is mostly to not worry about it too much since we are living in the promised land of fast mobile connections. Obviously there are a huge amount of users, connections and devices on https://www.keskikirjastot.fi , and I should be aiming to create a solution that works reasonably well in all cases. Packet loss is something iv'e never really thought of that much, tools for testing and tips for improving the experience in these cases are always welcome.

**Comment by sjuvonen** [comment] 2019-05-02 15:06
Realtime schedule rebuilds were broken due to a recent change in related code. Now it is fixed again.

https://github.com/libraries-fi/kirkanta/commit/7a26ba8125c36228bb8c75fc227f9b8e322091c5

**Comment by sjuvonen** [comment] 2019-05-02 15:14
Actually the original change was close to a month old... Nobody seems to notice...

https://github.com/libraries-fi/kirkanta/commit/e2063a4f28b3c90c019907d0f4f91583850858e0

**Comment by olli-suutari-jkl** [comment] 2019-05-03 07:50
Hurrah, the "realtime" updates appear to be working!

However, there are some issues with changing the schedule starting date (and/or) fetching schedules from the past.

I changed the starting date of the Kuhmoinen schedule to 2019-02-25. (at around 9.45)

https://api.kirjastot.fi/v4/schedules?library=85020&lang=en&period.start=0w&period.end=0w&refs=period&limit=5000&pretty 

returns the schedules normally and returns the refs.period with a correct validFrom date:

    "refs": {
        "period": {
            "333813": {
                "id": 333813,
                "library": 85020,
                "validFrom": "2019-02-25",
                "validUntil": null,
                "isException": false,
                "name": "Aukioloajat",
                "description": null
            }
        }
    }
https://gist.github.com/olli-suutari-jkl/12290098174668b8294c6eeea3d9ee1d


But:
https://api.kirjastot.fi/v4/schedules?library=85020&lang=en&period.start=-1w&period.end=-1w&refs=period&limit=5000

does not return "anything".

{"type":"schedules","total":null,"items":[],"refs":{"period":{}}}

Edit: The issue appears to be limited to v4, since https://www.finna.fi/OrganisationInfo/Home?id=Keski#85020 fetches past schedules for Kuhmoinen w/o any issues.

**Comment by sjuvonen** [comment] 2019-05-03 11:43
Changing past schedules is not allowed because users would most likely only screw them up unintentionally. There is no need to create schedules into the past as there is no use-case for that. The only supported case would be for statistics and this is also the reason why users are blocked from modifying the past.

Right now schedule modification apply starting Monday of the running week so that weekly tables could be fixed if there has been an error.

This restriction applies to API v3 as well;
https://github.com/libraries-fi/legacy-kirkanta/blob/master/module/ScheduleGenerator/src/Subscriber/GenerateSchedules.php#L54
https://github.com/libraries-fi/legacy-kirkanta/blob/master/module/ScheduleGenerator/src/Controller/ScheduleController.php#L67

**Comment by olli-suutari-jkl** [comment] 2019-05-03 12:16
There are differences in between v3 and v4, since v3 returns the results from the “past" correctly:
https://api.kirjastot.fi/v3/library/85020?with=schedules&lang=en&period.start=-1w&period.end=-1w
https://gist.github.com/olli-suutari-jkl/a0530b83de39edeb4e279ec743d346cb

I find the situation where the maintainers have forgotten to fill in the schedules in time or decide to re-create them for whatever reason to be plausible.

In case of Kuhmoinen, we had to re-create the default schedules since there were none.
The same schedules were valid in the past, but now there are none.

Our widget supports navigating schedules backwards up to 8 weeks. (Probably useful for the curious minds or verifying if library was open/closed at some point and possibly tracing errors in the past schedules).

It also hides the schedules entirely if none are found for the initial week, week position is stored in a variable, thus if you were browsing past schedules of lib x and switched to Kuhmoinen, schedules would be hidden entirely. ( https://www.keskikirjastot.fi/web/arena/kirjastot?kuhmoisten-paakirjasto )

This just seems like a bug to me, but if it is by design the “bug” would be in https://kirkanta.kirjastot.fi/ UI where the users are allowed to pick past dates when it should be blocked.

**Comment by sjuvonen** [comment] 2019-05-03 12:28
Just accept that for some libraries there will be no schedules into the past, there is no other solution to it.  For reference, in Kirjastohakemisto it is not possible to navigate into the past weeks at all.

**Comment by sjuvonen** [comment] 2019-05-03 12:35
You can see from the period ID that API v3 is returning ghost schedules from the period that existed before. This is because the cache for the old API is not rebuilt when data is migrated from new Kirkanta to the old environment. This is also how it will be until we can shutdown the legacy APIs altogether.

**Comment by olli-suutari-jkl** [comment] 2019-05-03 13:38
Thanks for the clarification, I have adjusted the widget design to reflect this and opened a new issue for kirkanta. ^^.

**Closed as completed** 2019-06-06 09:02 UTC
